### ISSUE TITLE
mineralt false positives for googletag and addthis

### ISSUE THREAD

**Issue by hpr** [xd4rker/MinerBlock#21] opened 2018-03-21 21:08 UTC
on pages like this one: https://jsfiddle.net/gryzzly/urmwF/

minerblock outputs "[+] Mineralt miner found, stopping..." to the console, for this['addthis'], but really there is no miner. it's because this['addthis'] makes anything you put after it a function, so just as this['addthis'].db is a function, so is this['addthis'].foobar, etc.

this['googletag'] does the same thing and is similarly flagged. using minerblock v1.1.18.

**Comment by xd4rker** [comment] 2018-03-21 21:33
Thanks for reporting this! Unfortunately I'm not able to reproduce it. Which browser are you using ?

**Comment by hpr** [comment] 2018-03-22 00:06
oh, I'm using firefox 52 ESR (specifically IceCat) which may have something to do with it. I'll try testing it on a regular ESR install if it helps.

**Comment by hpr** [comment] 2018-03-22 01:36
oh, I'm using firefox 52 ESR (specifically IceCat) which may have something to do with it. I'll try testing it on a regular ESR install if it helps.

**Comment by hpr** [comment] 2018-03-22 01:36
did not mean to close, my bad

**Comment by xd4rker** [comment] 2018-03-24 14:52
Hi, I haven't been able to reproduce this on IceCat 52.6.0. Can you tell me the exact version and the OS you're using? Thanks.

![](https://i.imgur.com/qOJeqjp.png)

**Comment by Rub3nCT** [comment] 2018-06-17 17:56
Here you have another example: https://demo.themefuse.com/paradisecove/
![falsepositive](https://user-images.githubusercontent.com/5614990/41510631-72b39a2a-7268-11e8-8260-632b6b07dd6d.png)

**Comment by xd4rker** [comment] 2018-06-17 18:13
@Rub3nCT Thanks! This will be fixed in the next update.

**Closed** 2018-07-15 11:20 UTC
Labels: bug
